# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Set up base box as centos/7. Most be at least version 7
  # to use Docker.
  config.vm.box = "centos/7"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  config.vm.network "forwarded_port", guest: 9117, host: 9117
  config.vm.network "forwarded_port", guest: 2375, host: 2375

  # Virtualbox provider-specific configuration
  config.vm.provider "virtualbox" do |vb|
     # Display the VirtualBox GUI when booting the machine
     # vb.gui = true

     # Customize the amount of memory on the VM:
     vb.name = "ovs-exporter"
     vb.memory = "8192"
  end

  # Provision with bootstrap.sh
  config.vm.provision "file", source: "../../ovs_exporter", destination: "/ovs_exporter"
  config.vm.provision :shell, :path => "bootstrap.sh"
end